services:
  - type: web
    name: youtube-download
    env: node
    region: oregon
    branch: deploy/backend-render
    rootDir: ./backend
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 3333